#!/usr/bin/env bash
# Migration pack: Enter (LAB) → GLM 5.2
# Lightweight archive — excludes regenerable node_modules/.next/.git
# Includes everything needed to run `bun install && bun run dev` on the other side.
set -euo pipefail

TS=$(date +%Y%m%d-%H%M%S)
PROJ=/home/z/my-project
OUT_DIR="$PROJ/download"
BACKUP_NAME="Enter-migrate-to-glm52-$TS"
BACKUP_TAR="$OUT_DIR/$BACKUP_NAME.tar.gz"
STAGING="/tmp/enter-migrate-$$"

mkdir -p "$STAGING/Enter"

# MIGRATION.md — instructions for GLM 5.2 environment
cat > "$STAGING/Enter/MIGRATION.md" <<'EOF'
# Enter — Migration Pack (LAB → GLM 5.2)

This archive contains the full **Enter** codebase, ready to migrate to a GLM 5.2 environment.

## Quick start (3 commands)
```bash
tar -xzf Enter-migrate-to-glm52-*.tar.gz
cd Enter
bun install && bunx prisma generate && bunx prisma db push && bun run dev
```
App will be live at http://localhost:3000

## What's included
- `src/` — full Next.js 16 source (App Router, components, lib, API routes)
- `prisma/` — schema.prisma (SQLite, models: Session, Gene, Invention)
- `db/` — current SQLite database (preserves sessions history)
- `public/` — static assets
- `.env` — ZAI_API_KEY (already set, works in new env)
- All config files: package.json, tsconfig.json, next.config.ts, tailwind.config.ts,
  postcss.config.mjs, eslint.config.mjs, components.json, .gitignore, Caddyfile
- `mini-services/` — auxiliary services
- `scripts/` — backup & utility scripts

## What's excluded (regenerable)
- `node_modules/` — run `bun install` to regenerate (1.2 GB)
- `.next/` — build artifacts, regenerated by `bun run dev` or `bun run build`
- `.git/` — version history (migration is about code, not history)
- `skills/` — agent meta-tooling (61 MB), not part of the running app
- `dev.log`, `server.log`, `tsconfig.tsbuildinfo`, `tool-results/`, `download/`

## Architecture
- **Stack**: Next.js 16 (Turbopack) + TypeScript + Prisma 6 + SQLite + Tailwind + shadcn/ui
- **AI**: z-ai-web-dev-sdk (LLM chat + web_search function calling)
- **Pipeline**: 5-agent SSE streaming
  1. Problem Analyst (theory layer)
  2. Gene Extractor (repo-first — searches GitHub for real repos as "genes")
  3. AHI Ethicist (autonomy/ethics/decentralization scoring)
  4. Fusion Strategist (combines genes + produces patent claim)
  5. System Architect (final audit + AHI scoring)
- **6 critical layers**: Teoria → Repozytoria → Geny → AHI → Fuzja → Patent
- **Key files**:
  - `src/app/api/invent/route.ts` — SSE endpoint with 15s heartbeat
  - `src/lib/agents.ts` — 5 agent prompts
  - `src/lib/zai.ts` — ZAI SDK singleton
  - `src/lib/db.ts` — Prisma client
  - `src/components/lab/` — UI (top-bar, sidebar, invent-view, about-view, sessions-view, graph-view)

## Environment requirements
- Node.js 20+ (or Bun 1.1+)
- `ZAI_API_KEY` env var (already in .env)
- ~1.5 GB free disk (for node_modules after install)

## History
- v1: AHI Innovation Lab
- v2: Engine (genetic reconceptualization + patent framing)
- v3: Enter (final naming — current state)

## Post-migration checklist
- [ ] `bun install` succeeds
- [ ] `bunx prisma generate` succeeds
- [ ] `bunx prisma db push` succeeds (creates db/dev.db if missing)
- [ ] `bun run dev` serves http://localhost:3000 with HTTP 200
- [ ] Top bar shows "Enter" label with DNA icon
- [ ] Invent pipeline completes end-to-end (test with prompt: "System mapy myśli który działa offline i synchronizuje P2P")
EOF

# Copy project files with excludes
# skills/ = agent meta-tooling (61 MB), not part of the running Enter app
# upload/ = 1.7 MB of uploaded user files — kept (small, may contain user data)
rsync -a \
  --exclude='node_modules' \
  --exclude='.next' \
  --exclude='.git' \
  --exclude='dev.log' \
  --exclude='server.log' \
  --exclude='tsconfig.tsbuildinfo' \
  --exclude='tool-results' \
  --exclude='download' \
  --exclude='scripts/_restore_staging_*' \
  --exclude='.zscripts' \
  --exclude='skills' \
  "$PROJ/" "$STAGING/Enter/"

# Remove the staging scripts we don't want to ship
rm -rf "$STAGING/Enter/scripts/_restore_staging_"* 2>/dev/null || true

# Create tarball
tar -czf "$BACKUP_TAR" -C "$STAGING" Enter

# Report
SIZE=$(du -h "$BACKUP_TAR" | cut -f1)
FILES=$(tar -tzf "$BACKUP_TAR" | wc -l)
echo "Migration pack created: $BACKUP_TAR"
echo "  Size: $SIZE"
echo "  Files: $FILES"

# Cleanup
rm -rf "$STAGING"

# SHA256
cd "$OUT_DIR"
sha256sum "$(basename "$BACKUP_TAR")" > "$(basename "$BACKUP_TAR").sha256"
echo "Checksum: $(basename "$BACKUP_TAR").sha256"
